version: "3.7"

services:
  backend:
    image: browserless/chrome:latest
    platform: linux/amd64
    ports:
      - 80:80
    volumes:
      - ./app:/app
    working_dir: /app
    command: "npm run dev"